on:
  push:
    tags:
      - 'v*'

name: Deploy Docs

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1
          persist-credentials: false

      - name: Build Docs
        run: |
          PATH=/home/runner/.local/bin:$PATH
          cd ./docs/
          pip install -r requirements.txt
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.DOCS_DEPLOY_TOKEN }}
          FOLDER: ./docs/_build/html
          REPOSITORY_NAME: miaowware/docs.miaow.io
          BRANCH: gh-pages
          TARGET_FOLDER: gridtools
          CLEAN: true